### ISSUE TITLE
add tag fail when new env

### ISSUE THREAD

**Issue by nonorze-VOXX** [jykuo-love-shiritori/twp#109]
**Describe the bug**
![image](https://github.com/jykuo-love-shiritori/twp/assets/93046487/0a5e8431-624e-4840-8eb2-a3e6ac684d0b)

**To Reproduce**
set up
1. mv .example.env .env
2. cd front 
3. mv .example.env .env
4. cd ..
5. docker-compose up
6. Sign up error
7. git switch main
8. docker-compose up --build
9. sign up work
10. git switch coupon_api
11. docker-compose up --build
12. add coupon tag fail

1. Go to 
![image](https://github.com/jykuo-love-shiritori/twp/assets/93046487/ded8dc3f-afaf-48ca-8efc-b9a3e911c311)

14. input tag Click on 'enter

15. See error

**Additional context**
Signup also failed like this first but fine after rebuild.

**Comment by Error0229** [comment]
Did you insert dummy data?

**Comment by nonorze-VOXX** [comment]
> Did you insert dummy data?

sign up or add tag need dummy data?

**Comment by NOOBDY** [comment]
seems like a migration issue

**Comment by nonorze-VOXX** [comment]
it worked.
But why it need the data and failed with empty db?

**Comment by Error0229** [comment]
If you are not seller, you can't add tag

**Comment by NOOBDY** [comment]
looking at the query, probably because the subquery selected nothing, resulting in `NULL`
when trying to insert into a `NOT NULL` column would cause this error

**Comment by Error0229** [comment]
Won't happen ever again.
