### ISSUE TITLE
upload image cropping and accept only image file

### ISSUE THREAD

**Issue by UGisBusy** [jykuo-love-shiritori/twp#112]
**Is your feature request related to a problem? Please describe.**
The upload icon function on ``edit shop info``, ``edit user info`` and possibly ``edit product`` have some problem:
- User can choose any file type to upload ( in the ``edit shop info`` and ``edit user info``, i block it but it's after it uploaded
- The image may be too large, too small or have wrong ratio.

**Describe the solution you'd like**
- Accept only image file:
  - find a why to only allow image type when choose file to upload
- Image cropping
  - use css to handle showing the image on icon, not just ``weight:100%``
  - process the uploaded image, crop it or scale it if too big or small.

**Comment by KatoToyoki** [comment]
do you mean that the `weight:100%` will cause the scale be wrong?

**Comment by UGisBusy** [comment]
at least it can fuck up ratio
but if we handle image and make it to ~1:1, than ``weight:100%`` is perfectly fine.

**Comment by KatoToyoki** [comment]
then you can [check here](https://github.com/jykuo-love-shiritori/twp/pull/110/files#diff-de93c0b0371443e35a692e81f49c192f291693be2533b8e2614562bcd99d0881) with  `objectFit: 'cover',`
you can check my pr you will see i change a way for scale, the news component and news individual page's images are cover now ( the scale will always be normal )

you can take `frontend/src/components/News.tsx` for reference
