### ISSUE TITLE
ambiguous type and name & lacks of object on doc

### ISSUE THREAD

**Issue by KatoToyoki** [jykuo-love-shiritori/twp#121]
**Describe the bug**
### ambiguous type and name
  - POST `/seller/coupon/{id}/tag`
  - POST `/seller/product/{id}/tag`
  1. the name `id` can be more specific, and its type perhaps should be `number`
  2. the name `tag_id` seems like an individual id but it actually is an object, and `name:string` will not work

### lacks of object
- GET `/seller/product/{id}` lacks of `expire_date`

**To Reproduce**
open [Swagger](http://localhost:8080/swagger///index.html)
go to 
1. [POST /seller/coupon/{id}/tag](http://localhost:8080/swagger///index.html#/Shop/post_seller_coupon__id__tag)
2. [POST /seller/product/{id}/tag](http://localhost:8080/swagger///index.html#/Shop/post_seller_product__id__tag)
3. [GET /seller/product/{id}](http://localhost:8080/swagger///index.html#/Shop/get_seller_product__id_)

**Screenshots**
### ambiguous type and name
  <img width="535" alt="image" src="https://github.com/jykuo-love-shiritori/twp/assets/92158595/c4e142bf-bf40-4e72-ab6e-f6282bb6d7af">
  <img width="535" alt="image" src="https://github.com/jykuo-love-shiritori/twp/assets/92158595/691af07d-6a83-4939-9256-a0a16947740b">

**Additional context**
N/A

**Comment by UGisBusy** [comment]
id here is string cus it's a path params.
as for the tag_id, i pass in this it works
```ts
{tag_id : Number}
```

**Comment by KatoToyoki** [comment]
i forgot to mention the `PATCH` issue here, maybe another issue or PR
