### ISSUE TITLE
Discount value overflow

### ISSUE THREAD

**Issue by Error0229** [jykuo-love-shiritori/twp#124]
**Describe the bug**
The current coupon's discount value is set to `DECIMAL(5, 2)` which is way too small to fit any number larger than 10^3.
**To Reproduce**
1. Add a coupon with `fixed` type and set discount value larger than 10^3

**How to fix**
May change the  `DECIMAL(5, 2)`  to `NUMERIC` or `DECIMAL(10, 2)` for more flexibility.

**Comment by KatoToyoki** [comment]
product has similar issue as well, when i test input price or stock, may encounter  `ERROR: numeric field overflow (SQLSTATE 22003)`
