### ISSUE TITLE
Port Figma into frontend

### ISSUE THREAD

**Issue by kryr34** [jykuo-love-shiritori/twp#13]
just do the skeleton screen first.
implement the interface first then implement the functionality.

## Check how we're doing
We will pr when a section is ready.

✔️: done and merged
⌛: pr and waiting for review
❌: not finished

### (A) Home & Error ✔️
- [x] / (index)
- [x] (401)
- [x] (402)
- [x] (403)

### (B) Discover & News ❌
- [x] /news/newsID
- [ ] /discover?pageNumber={pageNumber}

### (C) Login & Signup ✔️
- [x] /login
- [x] /signup

### (D) Info Settings ✔️
- [x] /user/info
- [x] /seller/info

### (E) ViewShop ✔️
- [x] /sellerID/shop
- [x] /seller/manageProducts
- [x] /seller/manageProducts/new
- [x] /seller/manageProducts/productID

### (F) Order ✔️
- [x] /buyer/order
- [x] /buyer/order/orderID
- [x] /seller/order/orderID
- [x] /seller/order

### (G) Cart ⌛
include cart view and the detail part
- [x] /buyer/cart 

### (H) Product ❌
- [ ] /product

###  (I) Coupon ✔️
- [x] /admin/manageCoupon
- [x] /admin/manageCoupon/couponID
- [x] /admin/manageCoupon/new
- [x] /seller/manageCoupon
- [x] /seller/manageCoupon/new
- [x] /seller/manageCoupon/couponID
- [x] /sellerCoupon
- [x] /coupon

### (J) Admin ManageUser ✔️
- [x] /admin/manageUser

### (K) Security ✔️
- [x] /user/security
- [x] /user/security/password
- [x] /user/security/manageCreditCard
- [x] /user/security/manageCreditCard/new

### (L) Search ❌
include search not found
- [ ] /search
- [ ] /search?shop={keyword}
- [ ] /search?keyword={keyword}

### (M) Report ❌
- [ ] /seller/report
- [ ] /seller/report/new
- [ ] /seller/report/reportID
- [ ] (the missing admin report)

**Comment by UGisBusy** [comment]
## Check how we're doing
We will pr when a section is ready.

### Home and Error
- [ ] / (index)
- [ ] (401)
- [ ] (402)
- [ ] (403)

### Discover & News
- [ ] /news/newsID
- [ ] /discover?pageNumber={pageNumber}

### Login & Signup
- [ ] /login
- [ ] /signup

### Info Settings
- [ ] /user/info
- [ ] /seller/info

### ViewShop
- [ ] /sellerID/shop
- [ ] /seller/manageProducts
- [ ] /seller/manageProducts/new
- [ ] /seller/manageProducts/productID

### Order
- [ ] /buyer/order
- [ ] /buyer/order/orderID
- [ ] /seller/order/orderID
- [ ] /seller/order

### Cart
include cart view and the detail part
- [ ] /buyer/cart 

### Product
- [ ] /product

### Coupon
- [ ] /admin/manageCoupon
- [ ] /admin/manageCoupon/couponID
- [ ] /admin/manageCoupon/new
- [ ] /seller/manageCoupon
- [ ] /seller/manageCoupon/new
- [ ] /seller/manageCoupon/couponID
- [ ] /sellerCoupon
- [ ] /coupon

### Admin ManageUser
- [ ] /admin/manageUser

### Security
- [ ] /user/security
- [ ] /user/security/password
- [ ] /user/security/manageCreditCard
- [ ] /user/security/manageCreditCard/new

### Search
include search not found
- [ ] /search
- [ ] /search?shop={keyword}
- [ ] /search?keyword={keyword}

### Report
- [ ] /seller/report
- [ ] /seller/report/new
- [ ] /seller/report/reportID
- [ ] (the missing admin report)
