### ISSUE TITLE
[frontend] crop the text if it's too long

### ISSUE THREAD

**Issue by UGisBusy** [jykuo-love-shiritori/twp#131]
**Is your feature request related to a problem? Please describe.**
Some components displays raw string. And when the string is very long it go thru the roof.

**Describe the solution you'd like**
write a function like 
```python
def cropText( text, limit ):
  if ( len(text) > limit ):
    return text[:limit] + '...'
  return text
```
than apply this at places where needed it.

**Additional context**
will need my partner to help fixing their parts if there's any.

**Comment by KatoToyoki** [comment]
`GoodsItem` or `News` in /components already have similar functionality, 
like ` {name.substring(0, 11)} {name.length > 13 ? '...' : ''}`
