### ISSUE TITLE
Defective password Regex

### ISSUE THREAD

**Issue by kryr34** [jykuo-love-shiritori/twp#147]
**Describe the bug**
Password can't include `[],.(){}":;'+-=_~` but no explain

**Screenshot**
![](https://media.discordapp.net/attachments/1193655223122665503/1193655659804229652/df27a37e11776e3d.png?ex=65ad8176&is=659b0c76&hm=44fee766dd33517ef965534ab5eec788054065d11b2eac696e4e5effc0e6e2bd&=&format=webp&quality=lossless&width=973&height=183)
![](https://media.discordapp.net/attachments/1193655223122665503/1193655660026544249/c89c9d8b2758c8bf.png?ex=65ad8176&is=659b0c76&hm=8eea4fbf79063b65ea79779c8e1a96384512bedb955276bb3f7b40abab6e9089&=&format=webp&quality=lossless&width=1176&height=330)

**Comment by kryr34** [comment]
I reviewed the backend's validation code and found that it accepts more characters than the frontend.
I think the term "special character" is too broad.

The sign-up page should list all legal characters (may be decided by frontend) for clarity.
Alternatively, transfer the responsibility for error reporting to the backend.

**Comment by UGisBusy** [comment]
if there're too many special characters, listing them all on ui is bad ux.
i can either
- delete the frontend validation part. show backend message sended.
- i list current special characters that count in frontend's validation

**Comment by kryr34** [comment]
Yes, this is exactly my meaning.

**Comment by UGisBusy** [comment]
![image](https://github.com/jykuo-love-shiritori/twp/assets/91419313/6421230a-d3c4-47eb-b245-a5fcb6300988)
> Password must be at least 8 characters long and contain: [a-z], [A-Z], [0-9], a special character(?=.*@$!%*?&[],.(){}":;'+-=_~).

is warning like this good enough?

**Comment by NOOBDY** [comment]
lgtm

**Comment by kryr34** [comment]
no comment
