### ISSUE TITLE
Add routing tests

### ISSUE THREAD

**Issue by NOOBDY** [jykuo-love-shiritori/twp#15]
**Is your feature request related to a problem? Please describe.**
Due to a recent breakage in Golang backend routing, we need to have some way of knowing if something important broke

**Describe the solution you'd like**
Implement a `/api/ping` endpoint for sanity checking and possibly run tests during CI build

**Additional context**
We COULD implement unit tests for every endpoint but that's up to backend developers

Reference: https://echo.labstack.com/docs/testing

**Comment by kryr34** [comment]
forgot to close
