### ISSUE TITLE
New product is disabled and can't be enable

### ISSUE THREAD

**Issue by Error0229** [jykuo-love-shiritori/twp#151]
**Describe the bug**
As title
The issue seems come from the misuse `enabled` with `enable`
the current `POST` request's content for creating product looks like
```form
name: flower
description: always please
image: (binary)
price: 20
expire_date: 2024-01-30T00:00:00.000Z
stock: 100
enable: true
tags: 19
```
**To Reproduce**
- Create any product as seller
- view corresponding shop's product as customer, can't find the product just create
- seller can't change the status of product too

**Expected behavior**
- There need a checkbox or button let seller to enable or disable the product
- The default value for `"enabled"` should be `true` when creating a new product

**Comment by x06lan** [comment]
Swagger has incorrectly set the "enabled" column as option when edit a product and the mistake lies in the default value, which should be set to false.
