### ISSUE TITLE
Credit card page downed when the user have no credit card

### ISSUE THREAD

**Issue by Error0229** [jykuo-love-shiritori/twp#152]
**Describe the bug**
As title
The bug seems to come from a lack of empty `JSON` handling.
**To Reproduce**
1. Create a new user
2. navigate to [user security page](http://localhost:8080/user/security)
3. Click credit card
4. Page downed

**Screenshots**
![image](https://github.com/jykuo-love-shiritori/twp/assets/52036774/360b67d3-3c59-4180-8156-7c9b21a83c1d)

**Comment by UGisBusy** [comment]
can backend make the default value of card empty array ``[]``?

**Comment by Error0229** [comment]
> can backend make the default value of card empty array `[]`?

Yes
