### ISSUE TITLE
Scrolling position is wrong

### ISSUE THREAD

**Issue by NOOBDY** [jykuo-love-shiritori/twp#22]
**Describe the bug**
Navigating to a product page will place the page in a scrolled position

**To Reproduce**
1. Go to 'home page'
2. Scroll down to view products
3. Click on any product 'more' buttons

**Expected behavior**
Navigating to a new page should place me at the top of the page

**Screenshots**
![image](https://github.com/jykuo-love-shiritori/twp/assets/48180490/6a6df8be-4427-478b-be7d-cc044b3e0f09)
![image](https://github.com/jykuo-love-shiritori/twp/assets/48180490/643be97d-dd84-4993-92c5-9376671a618a)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Comment by KatoToyoki** [comment]
i don't know why, but it seems that when clicking a new link, the position of height didn't reset, that is, the same with the height position of former page. 
so, when scrolling down to the button of the index then click "more" also transfer to the bottom of the discover page.

### fix plan :
using the following code within BrowserRouter
```ts
 useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);
  ```
  
 i tested it, and it can actually let you back to the top of the page, but the process is:
click link -> takes you to the former position with new page -> scroll to the top of the page
not transfer to the top of the new page after clicking the link.

i don't know if this method is acceptable.

**Comment by KatoToyoki** [comment]
btw, using `<a>` will not have this problem. but the flashing problem will exist.
i try to let both of the two problems to be controlled.

**Comment by NOOBDY** [comment]
what about this https://reactrouter.com/en/main/components/scroll-restoration

**Comment by NOOBDY** [comment]
> btw, using `<a>` will not have this problem. but the flashing problem will exist. i try to let both of the two problems to be controlled.

because `<a>` is a full page reload and `<Link>` is a simulated page transition done in react router

see more: https://reactrouter.com/en/main/components/link
