### ISSUE TITLE
ns_binding_aborted

### ISSUE THREAD

**Issue by x06lan** [jykuo-love-shiritori/twp#27]
**Describe the bug**

1. disable cache on firefox network tab
2. open http://localhost:8080/ with firefox

**Screenshots**

![screenshot-2023-11-01-15-15-10](https://github.com/jykuo-love-shiritori/twp/assets/52856456/9dbd65d0-3198-43b8-aad5-d77870880d95)

**Desktop (please complete the following information):**
 - OS: [e.g. archlinux]
 - Browser [firefox]

**Comment by KatoToyoki** [comment]
<img width="1275" alt="截圖 2023-11-01 下午4 33 53" src="https://github.com/jykuo-love-shiritori/twp/assets/92158595/e09f9616-b1a8-446b-b9b8-70f803ebcc11">

is it NORMAL that port 9090 also has the same issue?

**Comment by NOOBDY** [comment]
it's not our webpage so even if it's not normal it's out of our control

**Comment by NOOBDY** [comment]
personally i think if this doesn't affect performance that much (i mean we are using react anyways) we can ignore this problem

**Comment by KatoToyoki** [comment]
this issue only reveals on firefox. edge, chrome and safari all work fine.
i think we can mark it as wontfix
