### ISSUE TITLE
Migrate frontend's X-Large dev branch into the upstream repo

### ISSUE THREAD

**Issue by kryr34** [jykuo-love-shiritori/twp#38]
### Is your feature request related to a problem? Please describe.

The tremendous task #13 is scattered across branches in the front-end team.
To make it easier to track and better workflow, there should be a mainly dev branch

### Describe the solution you'd like

Integrate *some-relatived-things* into one dev branch on the upstream repo and using PRs
This ensures proper code review

### Describe alternatives you've considered

Let's wait for one more month and hope that all is well with the colossal PR

**Comment by UGisBusy** [comment]
obsolete

**Comment by kryr34** [comment]
this doesn't duplicate
