### ISSUE TITLE
Search on type

### ISSUE THREAD

**Issue by NOOBDY** [jykuo-love-shiritori/twp#76]
> constantly polling the DB when typing isn't optimal performance wise, it would be better if this was done in-memory or something like Redis

_Originally posted by @NOOBDY in https://github.com/jykuo-love-shiritori/twp/pull/67#discussion_r1410386030_

**Comment by NOOBDY** [comment]
This isn't an issue per se, but when implementing this in the frontend, it should add a delay to prevent DDOSing the backend when typing.

Something like:
```tsx
const SearchBar = () => {
  let timeout;
  const onType = async () => {
    clearTimeout(timeout);
    timeout = setTimeout(() => queryDB(), 100);
  }

  return (
    <>
      <!-- something -->
    </>
  );
}

**Comment by ntut-rick** [comment]
resolve in #134

**Comment by kryr34** [comment]
resolve in #134
