### ISSUE TITLE
Improve error handling in frontend Login

### ISSUE THREAD

**Issue by NOOBDY** [jykuo-love-shiritori/twp#93]
**Is your feature request related to a problem? Please describe.**
Currently the login flow only handles the happy path, if any error occurs, the program would hang and die

**Describe the solution you'd like**
Implement error checks and handle what to do when an error occurs

**Describe alternatives you've considered**
N/A

**Additional context**
Files(inside `frontend/src`): `pages/login.tsx`, `pages/authorize.tsx`, `pages/callback.tsx`, `components/AuthProvider.tsx`

**Comment by kryr34** [comment]
seems fix somewhere
