### ISSUE TITLE
[frontend] Calling API

### ISSUE THREAD

**Issue by UGisBusy** [jykuo-love-shiritori/twp#94]
## U know rule and so do i
✔️: done and merged
⌛: pr and waiting for review
❌: not finished

### (A) Discover & News TYK ✔️
- [x] /news/newsID
- [x] /discover?pageNumber={pageNumber}

### (B) ViewShop TYK ⌛
- [x] /sellerID/shop
- [x] /seller/manageProducts
- [x] /seller/manageProducts/new
- [x] /seller/manageProducts/productID

### (C) Order TYK ⌛
- [x] /buyer/order
- [x] /buyer/order/orderID
- [x] /seller/order/orderID
- [x] /seller/order

### (D) Product TYK ⌛
- [x] /product

### (E) Coupon UG ⌛
- [x] /admin/manageCoupon
- [x] /admin/manageCoupon/couponID
- [x] /admin/manageCoupon/new
- [x] /seller/manageCoupon
- [x] /seller/manageCoupon/new
- [x] /seller/manageCoupon/couponID
- [x] /sellerCoupon

### (F) Report TYK ✔️
- [x] /seller/report
- [x] /seller/report/reportID
- [x] /admin/report
- [x] /admin/report/reportID

### (G) Cart UG ❌
- [x] /buyer/cart 

### (H) Login & Signup UG ✔️
- [x] /login
- [x] /signup

### (I) Info Settings UG ✔️
- [x] /user/info
- [x] /seller/info

### (J) Admin ManageUser UG ⌛
- [x] /admin/manageUser 

### (K) Security UG ✔️
- [x] /user/security
- [x] /user/security/password
- [x] /user/security/manageCreditCard
- [x] /user/security/manageCreditCard/new

### (L) Search TYK ⌛
- [x] /search
- [-] /search?shop={keyword}
- [x] /search?keyword={keyword}

**Comment by kryr34** [comment]
34 tasks done and all PRs merged
